version: '3.3'

services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: